### ISSUE TITLE
Installation instructions unclear

### ISSUE THREAD

**Issue by themightyoarfish** [magazino/pylon_camera#21]
The instructions say

> The package has been tested for ROS-Indigo. For other ROS versions, please replace 'indigo' with your desired ROS-Version in the following install instructions.

However, the only part where `indigo` occurs is in 
`sudo sh -c 'echo "yaml https://raw.githubusercontent.com/magazino/pylon_camera/indigo-devel/rosdep/pylon_sdk.yaml " > /etc/ros/rosdep/sources.list.d/15-plyon_camera.list'`

Replacing `indigo` with something else will error since the file won't exist. So it's not clear if and how the installation instructions must be adapted for a different distro.

What's also not explicitly mentioned that that the Basler pylon5 camera driver must be installed before using these instructions. With that, installation on indigo seems to work without problems.

**Comment by andrejpan** [comment]
Strongly supporting to update the instructions.
