### ISSUE TITLE
Installation command to add yaml url to 15-pylon_camera.list broken.

### ISSUE THREAD

**Issue by Crusty82** [magazino/pylon_camera#24]
On ROS Wiki there is an extra semicolon that breaks this for me.

Command given on ROS Wiki (http://wiki.ros.org/pylon_camera)

sudo sh -c 'echo "yaml https://raw.githubusercontent.com/magazino/pylon_camera/indigo-devel/rosdep/pylon_sdk.yaml"; > /etc/ros/rosdep/sources.list.d/15-pylon_camera.list'

This simply prints "yaml https://raw.githubusercontent.com/magazino/pylon_camera/indigo-devel/rosdep/pylon_sdk.yaml" to the terminal for me instead of the file.

Easy fix: remove the semicolon to make this correct echo into a file.

Fixed command:
sudo sh -c 'echo "yaml https://raw.githubusercontent.com/magazino/pylon_camera/indigo-devel/rosdep/pylon_sdk.yaml" > /etc/ros/rosdep/sources.list.d/15-pylon_camera.list'

**Comment by marc-up** [comment]
Thanks for the feedback! Should be fixed now
