### ISSUE TITLE
FindPylon.cmake Fix

### ISSUE THREAD

**Issue by tlindbloom** [magazino/pylon_camera#27]
I could not get the package to build when the pylon5 package was installed in a different location than /opt. I got it to work by changing the second line in FindPylon.cmake from:
`if (NOT "${PYLON_ROOT}")`
to:
`if (NOT DEFINED ENV{PYLON_ROOT})`

**Comment by mgrrx** [comment]
Yep you are right. We fixed it internally and will publish it with our next release.
