### ISSUE TITLE
What is the best way to get snapshots from the package?  

### ISSUE THREAD

**Issue by matheusns** [magazino/pylon_camera#33]
Hello guys,
I'm developing an application that needs to get some snapshots. I'm using a callback and a loop (along with a ros::spinOnce) to get the frames, but sometimes, maybe for the loop, the frames stop to arrived into the callback.  Is there a way to improve this kind of operation?

**Comment by NikolasE** [comment]
Could you add some details? Do you get any error message? Is the action-interface still working?

**Comment by matheusns** [comment]
I'm not using the action to get the images yet, but I'd like to know more information about it, can I get images from it during a video stream? So, by now, I'm getting the snapshot from the streaming topic while it's on, but sometimes errors happen because the topic stops the publications.

**Comment by NikolasE** [comment]
But do you get any error messages? What is the output from the pylon_camera_node?

**Comment by matheusns** [comment]
There isn't any error, but some instability from the topic (sometimes it stops the publications), due probably for  the simultaneous streaming and snapshot. I'd like to know about the action, does it work during a continuous grabbing? Thanks for the attention.

**Comment by NikolasE** [comment]
I think it would be better if you post a question at answers.ros.org (with the tag 'pylon_camera') as it's more likely that there is a problem with the way you subscribe. Issues at github are thought for reporting bugs and feature requests and less for problems when using the node. At answers.ros, you could post your listener code and others could also help.
