### ISSUE TITLE
Fix typo in Tutorial

### ISSUE THREAD

**Issue by StudentCV** [magazino/pylon_camera#4]
Hey,
there is a typo in your tutorial over at http://wiki.ros.org/pylon_camera it says

/etc/ros/rosdep/sources.list.d/15-**plyon**_camera.list

instead of

/etc/ros/rosdep/sources.list.d/15-**pylon**_camera.list

it does not break anything so this does not have a high priority. Also, the distribution names do not necessarily need to be changed for e.g. `kinetic` as the branch `kinetic-devel` does not exist.

**Comment by NikolasE** [comment]
Hey!

Thanks for the hint, but It's a wiki page, so could can change typos yourself :)
