### ISSUE TITLE
Changing Capture Resolution

### ISSUE THREAD

**Issue by salemUC** [magazino/pylon_camera#53]
Hello,
I am using 
-Basler Ace acA4024-29uc camera, 
-USB interface, 
-ROS is Indigo ,
-Ubuntu 14.04
when I use pylon viewer software it allows me to change the resolution. However, with Pylon_camera ROS package I am not able to change the resolution down to 8 MP. I tried using the Binning option but it gives "Cam does not support binning…”.  Does anyone have a recommendation?

**Comment by SammyRamone** [comment]
This camera does not support binning
https://docs.baslerweb.com/#t=en%2Fbinning.htm
Are you sure that you set binning in the pylon viewer and not the area of interest?
