### ISSUE TITLE
The device is currently in use by another application! 

### ISSUE THREAD

**Issue by eyildiz-ugoe** [magazino/pylon_camera#54]
The camera is plugged, IP address is set, yet the PylonViewerApp cannot show an image from the camera. IP configuration page shows the warning of :

`The device is currently in use by another application!
Please close any applications currently using the device and click Refresh to check the status again.`

which is nonsense since no other application uses it. It's only PylonViewerApp that is problematic, I can use the camera on ROS without a problem. But when I just want to take a couple of pictures, this shows up and I cannot take images.

Quite annoying.

**Comment by uliklank** [comment]
For issues with the PylonViewerApp please directly contact Basler, since it is not part of this repository.
